services:
  proxy-tool:
    platform: linux/amd64
    build:
      dockerfile: ./Dockerfile
    restart: unless-stopped
    mem_limit: 2G
    labels:
      - traefik.enable=true
      - traefik.http.routers.proxy-tool.entrypoints=web
      - traefik.http.routers.proxy-tool.rule=Host(`p.docker.localhost`)
