version: '3'

services:

    proxy-tool:
        platform: linux/amd64
        build:
          dockerfile: ./Dockerfile
        container_name: proxy-tool
        restart: unless-stopped
        ports:
          - 8000:8000
