services:
  proxy-tool:
    platform: linux/amd64
    build:
      dockerfile: ./Dockerfile
    restart: unless-stopped
    mem_limit: 2G
    volumes:
      - $PWD/.proxy-tool:/root/.proxy-tool
    labels:
      - traefik.enable=true
      - traefik.http.routers.proxy-tool.entrypoints=web
      - traefik.http.routers.proxy-tool.rule=Host(`p.docker.localhost`)

      # 临时屏蔽
      - traefik.http.routers.proxy-tool-nodeseek.entrypoints=web
      - traefik.http.routers.proxy-tool-nodeseek.rule=Host(`p.docker.localhost`) && PathPrefix(`/api/rss/nodeseek`)
      - traefik.http.middlewares.test-ipallowlist.ipallowlist.sourcerange=127.0.0.1/32
      - traefik.http.routers.proxy-tool-nodeseek.middlewares=test-ipallowlist
